# fly.toml app configuration file generated for monobank-integration on 2025-06-20T15:34:22+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'monobank-integration'
primary_region = 'waw'

[build]

[env]
  PORT = '3000'
  SCOPES = "read_orders,write_orders"
  SHOPIFY_API_KEY = '9abc85c06798b7b203bd30dd9cb4cfbe'
  SHOPIFY_APP_URL = 'https://monobank-integration.fly.dev'
  SHOPIFY_API_SECRET = '89af8a438a2f11e16980341624d5cd0e'
  DATABASE_URL = "file:/data/database.db"
  ENCRYPTION_SECRET = "sW2@nFp7v#5gY*JzR&bK9qX$cE6uH3mD"

[processes]
  app = 'node ./dbsetup.js npm run docker-start'

[[mounts]]
  source = 'data'
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
