# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9abc85c06798b7b203bd30dd9cb4cfbe"
name = "Monobank Intergration"
handle = "monobank-intergration"
application_url = "https://monobank-intergration.fly.dev/"
embedded = true

[build]
include_config_on_deploy = false

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "orders/create", "app/uninstalled" ]
  uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders"

[auth]
redirect_urls = [
  "https://monobank-intergration.fly.dev/auth/callback",
  "https://monobank-intergration.fly.dev/auth/shopify/callback",
  "https://monobank-intergration.fly.dev/api/auth/callback"
]

[pos]
embedded = false

[[app.navigation.links]]
label = "Settings"
destination = "/app/settings"
