# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9abc85c06798b7b203bd30dd9cb4cfbe"
name = "Monobank Intergration"
handle = "monobank-intergration"
application_url = "https://usable-rightly-puma.ngrok-free.app/"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "ORDERS_CREATE" ]
  uri = "/webhooks"


  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[auth]
redirect_urls = [ "https://usable-rightly-puma.ngrok-free.app/auth/callback", "https://usable-rightly-puma.ngrok-free.app/auth/shopify/callback", "https://usable-rightly-puma.ngrok-free.app/api/auth/callback" ]

[pos]
embedded = false

[app.navigation]
  [[app.navigation.links]]
    label = "Settings"
    destination = "/app/settings"