# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "74bc9e0d29ec8007decd1eb3b583ae97"
name = "way::more: Monobank"
handle = "waymore-mono-integration-pet"
application_url = "https://monobank-pet.fly.dev/"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled", "orders/create" ]
  uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders"

[auth]
redirect_urls = [
  "https://monobank-pet.fly.dev/auth/callback",
  "https://monobank-pet.fly.dev/auth/shopify/callback",
  "https://monobank-pet.fly.dev/api/auth/callback"
]

[pos]
embedded = false

[[app.navigation.links]]
label = "Settings"
destination = "/app/settings"
